### PR TITLE
fix ProjectionList{}.As method (issue #364)

### LINKED ISSUE #364: ProjectionList{ColumnList{...}}.As("some_alias")  results in no columns being rendered in the SQL
**Describe the bug**

ProjectionList.As method drops ColumnList columns.

**Environment (please complete the following information):**
 - OS: macosx
 - Database: mysql
-  Database driver: github.com/go-sql-driver/mysql 
 - Jet version v2.11.1

**Code snippet**

```go
strain := table.Strain
selects := mysql.ProjectionList{strain.AllColumns}.As("my_strain")
q := mysql.SELECT(selects).FROM(strain)
fmt.Println(q.DebugSql())
```
Output:
```
SELECT
FROM strain;
```

**Expected behavior**
I expected to see selected columns in the resulting SQL.

### PR DESCRIPTION
**Pull request by josephbuchma**
Fixes #364

### CODE REVIEW

File: internal/jet/projection.go [hunk 1]
```diff
@@ -45,6 +45,10 @@ func (pl ProjectionList) As(tableAlias string) ProjectionList {
 			newProjectionList = append(newProjectionList, p.As(tableAlias))
 		case ColumnExpression:
 			newProjectionList = append(newProjectionList, newAlias(p, tableAlias+"."+p.Name()))
+		case ColumnList:
```
Comment (go-jet) [inline internal/jet/projection.go:48]: Why not add `As` method on `ColumnList` as well, so we can write:

```golang
SELECT(strain.AllColumns.As("my_strain")).FROM(strain)
```

File: internal/jet/column_list.go [hunk 2]
```diff
@@ -39,6 +41,21 @@ func (cl ColumnList) Except(excludedColumns ...Column) ColumnList {
 	return ret
 }
 
+// As will create new projection list where each column is wrapped with a new table alias.
+// tableAlias should be in the form 'name' or 'name.*', or it can also be an empty string.
+// For instance: If projection list has a column 'Artist.Name', and tableAlias is 'Musician.*', returned projection list will
+// have a column wrapped in alias 'Musician.Name'. If tableAlias is empty string, it removes existing table alias ('Artist.Name' becomes 'Name').
+func (cl ColumnList) As(tableAlias string) ProjectionList {
+	if tableAlias > "" {
```
Comment (go-jet) [inline internal/jet/column_list.go:49]: Why `>`?

File: internal/jet/projection.go [hunk 3]
```diff
@@ -31,24 +31,30 @@ func (pl ProjectionList) serializeForProjection(statement StatementType, out *SQ
...
 
 // As will create new projection list where each column is wrapped with a new table alias.
-// tableAlias should be in the form 'name' or 'name.*'.
+// tableAlias should be in the form 'name' or 'name.*', or it can be an empty string, which will remove existing table alias.
 // For instance: If projection list has a column 'Artist.Name', and tableAlias is 'Musician.*', returned projection list will
-// have a column wrapped in alias 'Musician.Name'.
+// have a column wrapped in alias 'Musician.Name'. If tableAlias is empty string, it removes existing table alias ('Artist.Name' becomes 'Name').
 func (pl ProjectionList) As(tableAlias string) ProjectionList {
-	tableAlias = strings.TrimRight(tableAlias, ".*")
+	tableAliasWithDot := ""
```
Comment (go-jet) [inline internal/jet/projection.go:38]: Maybe `newTableAlias` would be better name, since alias might not contain a dot.

File: internal/jet/projection.go [hunk 4]
```diff
@@ -31,24 +31,30 @@ func (pl ProjectionList) serializeForProjection(statement StatementType, out *SQ
...
+	if tableAlias != "" {
+		tableAlias = strings.TrimRight(tableAlias, ".*")
+		tableAliasWithDot = tableAlias + "."
+	}
```
Comment (go-jet) [inline internal/jet/projection.go:43]: I think we can extract this (L38-42) into separate method like `reAlias` and use it in `ColumnList.As`, as there is no reason to have different behavior on `ProjectionList` and `ColumnList`.

**Comment by go-jet** [comment]
You'll also need to sync up with master, so the build can pass.

File: internal/jet/column_list.go (hunk 2 above)
Comment (josephbuchma) [reply internal/jet/column_list.go:49]: It's equivalent to `!=`, no particular reason. Will change to `!=`

File: internal/jet/projection.go (hunk 3 above)
Comment (go-jet) [reply internal/jet/projection.go]: Yeah, you right. Maybe `aliasPrefix`. Dunno.

File: internal/jet/utils.go [hunk 5]
```diff
@@ -278,3 +279,21 @@ func serializeToDefaultDebugString(expr Serializer) string {
...
+
+// joinAlias examples:
+//
+//	joinAlias("", "") // ""
+//	joinAlias("foo", "") // "foo"
+//	joinAlias("foo.*", "") // "foo"
+//	joinAlias("foo", "bar") // "foo.bar"
+//	joinAlias("foo.*", "bar") // "foo.bar"
+//	joinAlias("", "bar") // "bar"
+func joinAlias(tableAlias, columnAlias string) string {
```
Comment (go-jet) [inline internal/jet/utils.go:291]: Nice.

File: internal/jet/projection.go [hunk 6]
```diff
@@ -31,24 +29,26 @@ func (pl ProjectionList) serializeForProjection(statement StatementType, out *SQ
...
 
 // As will create new projection list where each column is wrapped with a new table alias.
-// tableAlias should be in the form 'name' or 'name.*'.
+// tableAlias should be in the form 'name' or 'name.*', or it can be an empty string, which will remove existing table alias.
 // For instance: If projection list has a column 'Artist.Name', and tableAlias is 'Musician.*', returned projection list will
-// have a column wrapped in alias 'Musician.Name'.
+// have a column wrapped in alias 'Musician.Name'. If tableAlias is empty string, it removes existing table alias ('Artist.Name' becomes 'Name').
 func (pl ProjectionList) As(tableAlias string) ProjectionList {
-	tableAlias = strings.TrimRight(tableAlias, ".*")
+	tableAlias = joinAlias(tableAlias, "")
```
Comment (go-jet) [inline internal/jet/projection.go:36]: This line looks redundant. As well as utils.go: L295-297.

Comment (josephbuchma) [reply internal/jet/projection.go]: Removed redundant logic.

**Comment by go-jet** [comment]
Thanks. Looks good.
